/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibrariManagement;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Biplob
 */
public class User_info extends javax.swing.JFrame {

    /**
     * Creates new form User_info
     */
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String connect = "jdbc:mysql://localhost:3306/";
    String schema = "library_managment";
    String user = "root";
    String DBpss = "apcl123456";
    byte[] personImg;

    public User_info() {
        initComponents();
        winProfile();
        uset_id_Auto_Insrement();
        demoImage();
        windowProfile();
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (Exception e) {
        }
         try {
            this.setIconImage(ImageIO.read(new File("resources\\library.png")));
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void windowProfile() {
        Toolkit tolkit = this.getToolkit();
        Dimension winSize = tolkit.getScreenSize();

        this.setLocation(winSize.width / 8, winSize.height / 6);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        user_pic = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lbl_set_img = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        btn_upload = new javax.swing.JButton();
        btn_save_img = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_nid_no = new javax.swing.JTextField();
        tf_adrss = new javax.swing.JTextField();
        tf_birth_day = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_mothrs_nm = new javax.swing.JTextField();
        tf_phon_no = new javax.swing.JTextField();
        tf_father_nm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pf_pass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        pf_rePass = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        tf_user_id = new javax.swing.JTextField();
        tf_fst_nm = new javax.swing.JTextField();
        tf_lst_nm = new javax.swing.JTextField();
        tf_eml = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        cbx_gender = new javax.swing.JComboBox<>();
        btn_close = new javax.swing.JButton();
        lbl_valid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(98, 26, 74));
        jPanel1.setForeground(new java.awt.Color(0, 153, 170));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setPreferredSize(new java.awt.Dimension(327, 489));

        user_pic.setBackground(new java.awt.Color(204, 204, 204));
        user_pic.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_set_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_set_img, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_upload.setText("Upload Image");
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });

        btn_save_img.setText("?");
        btn_save_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_imgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btn_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btn_save_img)))
                .addGap(26, 26, 26))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_save_img)
                .addContainerGap())
        );

        javax.swing.GroupLayout user_picLayout = new javax.swing.GroupLayout(user_pic);
        user_pic.setLayout(user_picLayout);
        user_picLayout.setHorizontalGroup(
            user_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_picLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(user_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        user_picLayout.setVerticalGroup(
            user_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_picLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Mather's Name");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("NID_No");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Phone_no ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Father's Name");

        tf_nid_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nid_noKeyTyped(evt);
            }
        });

        tf_birth_day.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_birth_dayFocusLost(evt);
            }
        });
        tf_birth_day.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_birth_dayKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Address");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Date of Birth");

        tf_phon_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_phon_noKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_phon_noKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("First_Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Last_Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Email");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Gender");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Re-Type Pass");

        tf_user_id.setEditable(false);

        tf_eml.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_emlFocusLost(evt);
            }
        });
        tf_eml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_emlKeyReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("User_ID");

        btn_submit.setText("Register");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        cbx_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", " " }));

        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pf_rePass)
                            .addComponent(pf_pass)
                            .addComponent(tf_lst_nm)
                            .addComponent(tf_fst_nm)
                            .addComponent(tf_user_id)
                            .addComponent(tf_eml)
                            .addComponent(cbx_gender, 0, 129, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_father_nm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_phon_no, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(tf_nid_no)
                            .addComponent(tf_birth_day)
                            .addComponent(tf_adrss)
                            .addComponent(tf_mothrs_nm, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_valid, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_close)
                        .addGap(18, 18, 18)
                        .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_user_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_fst_nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_lst_nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(pf_rePass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_eml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbx_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_phon_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(tf_father_nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(tf_mothrs_nm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tf_adrss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_birth_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nid_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_close)
                    .addComponent(lbl_valid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user_pic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String fileNm;
    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
         JFileChooser chose = new JFileChooser();
         chose.setFileSelectionMode(JFileChooser.FILES_ONLY);
         int res = chose.showOpenDialog(User_info.this);
         if(res == JFileChooser.APPROVE_OPTION){
             File file = chose.getSelectedFile();
             fileNm = file.getAbsolutePath();
             //tf_picture_pth.setText(fileNm);
             ImageIcon image = new ImageIcon(file.getAbsolutePath());
             Rectangle rect = lbl_set_img.getBounds();
             Image scaledimage = image.getImage().getScaledInstance(rect.width, rect.height, Image.SCALE_DEFAULT);
             image = new ImageIcon(scaledimage);
             lbl_set_img.setIcon(image);
         }       
        try {
            String file = null;
            FileInputStream fis = new FileInputStream(file);
            ByteArrayOutputStream bAos = new ByteArrayOutputStream();
            byte[] buff = new byte[1024];
            for (int readNum; (readNum = fis.read(buff)) != -1;) {
                bAos.write(buff, 0, readNum);
            }
            personImg = bAos.toByteArray();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_uploadActionPerformed
    
    private void demoImage() {
        File f = new File("resources\\library.png");
        try {
            fileNm = f.getAbsolutePath();
        } catch (Exception e) {
        }
        lbl_set_img.setIcon(new ImageIcon(new ImageIcon(fileNm).getImage().getScaledInstance(lbl_set_img.getWidth(), lbl_set_img.getHeight(), Image.SCALE_DEFAULT)));
        try {
            File image = new File(fileNm);
            FileInputStream fis = new FileInputStream(image);
            BufferedImage image2 = ImageIO.read(image);

            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            byte[] buff = new byte[1024];
            for (int readNum; (readNum = fis.read(buff)) != -1;) {
                baos.write(buff, 0, readNum);
            }
            personImg = baos.toByteArray();
        } catch (Exception e) {

        }

    }
    
    
    
    
    public void clearUserInfo(){
            tf_user_id.setText("");
            tf_fst_nm.setText("");
            tf_lst_nm.setText("");
            pf_rePass.setText("");
            pf_pass.setText("");
            tf_eml.setText("");
            tf_phon_no.setText("");
            tf_father_nm.setText("");
            tf_mothrs_nm.setText("");
            tf_adrss.setText("");
            tf_birth_day.setText("");
            tf_nid_no.setText("");
        }
    
    
    
    private void btn_save_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_imgActionPerformed
//        String sql = "update login_table set user_face_pic =? where User_ID = ?";
//        try {
//            pst = con.prepareStatement(sql);
//            pst.setBytes(1, personImg);
//            pst.setString(2, tf_user_id.getText());
//
//            pst.execute();
//            JOptionPane.showMessageDialog(rootPane, "Images Saved !");
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, e);
//        }
    }//GEN-LAST:event_btn_save_imgActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed

        if (tf_user_id.getText().isEmpty() || tf_fst_nm.getText().isEmpty() || tf_lst_nm.getText().isEmpty() || pf_pass.getText().isEmpty() || pf_rePass.getText().isEmpty()
            || tf_eml.getText().isEmpty() || tf_phon_no.getText().isEmpty() || tf_father_nm.getText().isEmpty() || tf_mothrs_nm.getText().isEmpty()|| tf_adrss.getText().isEmpty()|| tf_birth_day.getText().isEmpty()
            || tf_nid_no.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Insert All Feild !! ");
        } else {
            insrtReasers();
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        this.dispose();
        Log_In_Window lg  =new Log_In_Window();
        lg.setVisible(true);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void tf_nid_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nid_noKeyTyped
        // TODO add your handling code here:
        
        String strMobile = tf_nid_no.getText();
        char key =evt.getKeyChar();
        if (!(Character.isDigit(key) && (strMobile.length() < 17))) {
            evt.consume();
        }
    }//GEN-LAST:event_tf_nid_noKeyTyped

    private void tf_emlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_emlKeyReleased
        // TODO add your handling code here:
        
        String get_txt = tf_eml.getText();
        String get_v ="^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$" ;
        if(!get_txt.matches(get_v)){
            lbl_valid.setText("email is not valid");
            lbl_valid.setForeground(Color.red);
        }else {
            lbl_valid.setText("email is valid");
            lbl_valid.setForeground(Color.BLUE);
        }
    }//GEN-LAST:event_tf_emlKeyReleased

    private void tf_birth_dayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_birth_dayKeyReleased
        // TODO add your handling code here:
        String get_txt = tf_birth_day.getText();
        String get_v ="^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)"
                + "(?:0?[1,3-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)"
                + "0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|"
                + "(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)"
                + "(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$" ;
        
        if(tf_birth_day.getText().equals("")){
            lbl_valid.setText("");
        
        }else if(!get_txt.matches(get_v)){
            lbl_valid.setText("Date is not valid");
            lbl_valid.setForeground(Color.red);
        }else {
            lbl_valid.setText("Date is valid");
            lbl_valid.setForeground(Color.BLUE);
        }
        
    }//GEN-LAST:event_tf_birth_dayKeyReleased

    private void tf_emlFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_emlFocusLost
        // TODO add your handling code here:
        lbl_valid.setText("");
        
    }//GEN-LAST:event_tf_emlFocusLost

    private void tf_birth_dayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_birth_dayFocusLost
        // TODO add your handling code here:
        lbl_valid.setText("");
        
    }//GEN-LAST:event_tf_birth_dayFocusLost

    private void tf_phon_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_phon_noKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_phon_noKeyReleased

    private void tf_phon_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_phon_noKeyTyped
        // TODO add your handling code here:
         String strMobile = tf_phon_no.getText();
        char key = evt.getKeyChar();
        if (!(Character.isDigit(key) && (strMobile.length() < 11))) {
            evt.consume();
        }
        
    }//GEN-LAST:event_tf_phon_noKeyTyped
    public void insrtReasers() {
        
        int get_id = Integer.parseInt(tf_user_id.getText());
        String fst_name = tf_fst_nm.getText();
        String lst_name = tf_lst_nm.getText();
        String get_pass = "";
        if (pf_pass.getText().matches(pf_rePass.getText())) {
            get_pass = pf_pass.getText();
        } else {
            JOptionPane.showMessageDialog(rootPane, "pleas re-type your Correct password");
        }

        String get_emal = tf_eml.getText();
        String get_gndr = cbx_gender.getSelectedItem().toString();
        String get_phone_no = tf_phon_no.getText();
        String get_fatr_nm = tf_father_nm.getText();
        String get_mothr_nm = tf_mothrs_nm.getText();
        String get_addrss = tf_adrss.getText();
        String get_birth_day = tf_birth_day.getText();
        String get_nid = tf_nid_no.getText();
        int get_int = 0;
        
        try {
            InputStream is = new FileInputStream(new File(fileNm));
            con = DriverManager.getConnection(connect + schema, user, DBpss);
            pst = con.prepareStatement("INSERT INTO login_table values (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ");
            pst.setInt(1, get_id);
            pst.setString(2, fst_name);
            pst.setString(3, lst_name);
            pst.setString(4, get_pass);
            pst.setString(5, get_emal);
            pst.setString(6, get_gndr);
            pst.setString(7, get_phone_no);
            pst.setString(8, get_fatr_nm);
            pst.setString(9, get_mothr_nm);
            pst.setString(10, get_addrss);
            pst.setString(11, get_birth_day);
            pst.setString(12, get_nid);
            pst.setBlob(13, is);
            pst.setInt(14, get_int);
            int e = pst.executeUpdate();
            pst.close();
            if (e > 0) {
                JOptionPane.showMessageDialog(rootPane, "Insert Is Success");
                clearUserInfo();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Insert Is not Success");
            }

        } catch (SQLException ex) {
            ex.getSQLState();
            ex.getMessage();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        //showUser();
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_info().setVisible(true);
            }
        });
    }
        
    private void uset_id_Auto_Insrement(){
        try {
            con = DriverManager.getConnection(connect + schema, user, DBpss);
            String sqlS = "select max(User_ID) from login_table;";
            pst = con.prepareStatement(sqlS);
            rs = pst.executeQuery();
            if(rs.next()){
                //iss_id = rs.getInt(1)+1;
                tf_user_id.setText(String.valueOf(rs.getInt(1)+1));
            }else{
                System.out.println("isuu id not found");
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    
    
    }
    
    
    
    
    public void winProfile() {
        Toolkit tolkit = this.getToolkit();
        Dimension winSize = tolkit.getScreenSize();

        this.setLocation(winSize.width / 18, winSize.height / 8);
        //this.setResizable(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_save_img;
    private javax.swing.JButton btn_submit;
    private javax.swing.JButton btn_upload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbx_gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_set_img;
    private javax.swing.JLabel lbl_valid;
    private javax.swing.JPasswordField pf_pass;
    private javax.swing.JPasswordField pf_rePass;
    private javax.swing.JTextField tf_adrss;
    private javax.swing.JTextField tf_birth_day;
    private javax.swing.JTextField tf_eml;
    private javax.swing.JTextField tf_father_nm;
    private javax.swing.JTextField tf_fst_nm;
    private javax.swing.JTextField tf_lst_nm;
    private javax.swing.JTextField tf_mothrs_nm;
    private javax.swing.JTextField tf_nid_no;
    private javax.swing.JTextField tf_phon_no;
    private javax.swing.JTextField tf_user_id;
    private javax.swing.JPanel user_pic;
    // End of variables declaration//GEN-END:variables
}
